LAB : Multi Container Pods
Creating Multi Container Pods


file: multi_container_pod.yml

apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    tier: front
    app: nginx
    role: ui
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: data
          mountPath: /var/www/html-sample-app
 
    - name: sync
      image: schoolofdevops/sync:v2
      volumeMounts:
        - name: data
          mountPath: /var/www/app
 
  volumes:
    - name: data
      emptyDir: {}
To create this pod

kubectl apply -f multi_container_pod.yml
Check Status

root@kube-01:~# kubectl get pods
NAME      READY     STATUS              RESTARTS   AGE
nginx     0/2       ContainerCreating   0          7s
vote      1/1       Running             0          3m
Checking logs, logging in

kubectl logs  web  -c sync
kubectl logs  web  -c nginx
 
kubectl exec -it web  sh  -c nginx
kubectl exec -it web  sh  -c sync
 
Observe whats common and whats isolated in two containers running inside the same pod using the following commands,

shared

hostname
ifconfig
isolated

cat /etc/issue
ps aux
df -h
